/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Modos.mod3;

import Modos.mod1.*;
import classes.Questão;

import classes.Estados;
import classes.MapaEstadosBrasil;
import classes.Mapa;
import javax.swing.ImageIcon;
import java.io.IOException;
import Modos.NewJFrame1;
import classes.MapaMundiOceanos;
import classes.Pais;
import classes.continente;
import classes.oceano;
import java.awt.Image;
import java.awt.List;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import java.util.Random;
import java.util.Set;
import java.util.TreeSet;
import javax.swing.JOptionPane;

/**
 *
 * @author alexsander
 */
public class Form3 extends javax.swing.JFrame {

    int questao = 0;

    MapaMundiOceanos[] MapMundiOceanos;
    private static Mapa map = new Mapa();
    public static Random RND = new Random();

    private static oceano oceano = new oceano();
    private static continente continente = new continente();
    private static Pais pais = new Pais();
    private static Questão guest = new Questão();

    public void Modifica() {
        int i1 = 0, i2 = 0, i3 = 0, i4 = 0, i5 = 0;
        int pc = RND.nextInt(14);
        int pc1 = RND.nextInt(4);
        while (i1 == 0) {
            if (pc1 == 0 || pc1 < 3) {
                i1 = 1;
                saturno.setText(oceano.oceano[pc1]);
            }
            else
                pc1 = RND.nextInt(4);
        }
        while (i2 == 0) {
            if (pc == 0 || pc < 5) {
                i2 = 1;
                jupiter.setText(pais.Pais[pc]);
            }
            else
                pc = RND.nextInt(14);
        }
        while (i3 == 0) {
            if (pc > 4 || pc < 10) {
                i3 = 1;
                urano.setText(pais.Pais[pc]);
            }
            else
                pc = RND.nextInt(14);
        }
        while (i4 == 0) {
            if (pc1 > 2 || pc1 < 5) {
                i4 = 1;
                marte.setText(oceano.oceano[pc1]);
            }
            else
                pc1 = RND.nextInt(4);
        }
        while (i5 == 0) {
            if (pc1 > 4 || pc1 < 7) {
                i5 = 1;
                mercurio.setText(continente.Continente[pc1]);
            }
            else
                pc = RND.nextInt(14);
        }
    }

    public Form3() {
        initComponents();
        MapMundiOceanos = new MapaMundiOceanos[255];
        MapMundiOceanos[0] = new MapaMundiOceanos(oceano.oceano[0], map.oceano[0]);
        MapMundiOceanos[1] = new MapaMundiOceanos(oceano.oceano[1], map.oceano[1]);
        MapMundiOceanos[2] = new MapaMundiOceanos(oceano.oceano[2], map.oceano[2]);
        MapMundiOceanos[3] = new MapaMundiOceanos(oceano.oceano[3], map.oceano[3]);
        MapMundiOceanos[4] = new MapaMundiOceanos(oceano.oceano[4], map.oceano[4]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        imagemMOD2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        seleciona_pla = new javax.swing.JLabel();
        mercurio = new javax.swing.JRadioButton();
        jupiter = new javax.swing.JRadioButton();
        saturno = new javax.swing.JRadioButton();
        marte = new javax.swing.JRadioButton();
        urano = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        imagemMOD2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/oceano/oceano atlantico.png"))); // NOI18N

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/proximo.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        seleciona_pla.setText("Selecione:");

        buttonGroup1.add(mercurio);
        mercurio.setText("Oceano Atlântico");
        mercurio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mercurioActionPerformed(evt);
            }
        });

        buttonGroup1.add(jupiter);
        jupiter.setText("Alemanha");
        jupiter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jupiterActionPerformed(evt);
            }
        });

        buttonGroup1.add(saturno);
        saturno.setText("Europa");
        saturno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saturnoActionPerformed(evt);
            }
        });

        buttonGroup1.add(marte);
        marte.setSelected(true);
        marte.setText("Oceano Pacífico");
        marte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marteActionPerformed(evt);
            }
        });

        buttonGroup1.add(urano);
        urano.setText("Brasil");
        urano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uranoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagemMOD2, javax.swing.GroupLayout.DEFAULT_SIZE, 658, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(mercurio)
                                .addGap(41, 41, 41)
                                .addComponent(jupiter))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(seleciona_pla)
                                .addGap(162, 162, 162)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(marte)
                        .addGap(45, 45, 45))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(saturno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(urano)
                        .addGap(147, 147, 147)))
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(imagemMOD2, javax.swing.GroupLayout.PREFERRED_SIZE, 547, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(seleciona_pla)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mercurio)
                            .addComponent(jupiter)
                            .addComponent(marte))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(saturno)
                            .addComponent(urano))
                        .addGap(17, 17, 17))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jupiterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jupiterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jupiterActionPerformed

    private void saturnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saturnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saturnoActionPerformed

    private void mercurioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mercurioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mercurioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        /*ImageIcon icon = new ImageIcon(MapEstadosBrasil[1].getMap());
         imagemMOD1.setIcon(icon);*/
        Modifica();
        questao++;
        if (questao == 1) {
            if (mercurio.isSelected() == true) {
                guest.questaoMod3(true);
            } else {
                guest.questaoMod3(false);
            }
            ImageIcon icon = new ImageIcon(MapMundiOceanos[1].getMap());
            imagemMOD2.setIcon(icon);
            jupiter.setText("Oceano Glacial Antártico");
        }//-------------------------------------------------------------------------------//
        else if (questao == 2) {
            if (jupiter.isSelected() == true) {
                guest.questaoMod3(true);
            } else {
                guest.questaoMod3(false);
            }
            ImageIcon icon = new ImageIcon(MapMundiOceanos[2].getMap());
            imagemMOD2.setIcon(icon);
            saturno.setText("Oceano Glacial Ártico");
        }//-------------------------------------------------------------------------------//
        else if (questao == 3) {
            if (saturno.isSelected() == true) {
                guest.questaoMod3(true);
            } else {
                guest.questaoMod3(false);
            }
            ImageIcon icon = new ImageIcon(MapMundiOceanos[3].getMap());
            imagemMOD2.setIcon(icon);
            urano.setText("Oceano índico");
        }//-------------------------------------------------------------------------------//      
        else if (questao == 4) {
            if (urano.isSelected() == true) {
                guest.questaoMod3(true);
            } else {
                guest.questaoMod3(false);
            }
            ImageIcon icon = new ImageIcon(MapMundiOceanos[4].getMap());
            imagemMOD2.setIcon(icon);
            marte.setText("Oceano Pacífico");
        }//-------------------------------------------------------------------------------// 
        else if (questao > 4) {
            if (marte.isSelected() == true) {
                guest.questaoMod3(true);
            } else {
                guest.questaoMod3(false);
            }
            this.setVisible(false);
            new NewJFrame1().setVisible(true);
            JOptionPane.showMessageDialog(null, "Modo 3 -> Término");
        }//-------------------------------------------------------------------------------//
    }//GEN-LAST:event_jButton1ActionPerformed

    private void marteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marteActionPerformed

    private void uranoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uranoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uranoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel imagemMOD2;
    private javax.swing.JButton jButton1;
    private javax.swing.JRadioButton jupiter;
    private javax.swing.JRadioButton marte;
    private javax.swing.JRadioButton mercurio;
    private javax.swing.JRadioButton saturno;
    private javax.swing.JLabel seleciona_pla;
    private javax.swing.JRadioButton urano;
    // End of variables declaration//GEN-END:variables
}
