/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Modos.mod1;

import classes.Questão;
import classes.Rodada;

import classes.Estados;
import classes.MapaEstadosBrasil;
import classes.Mapa;
import javax.swing.ImageIcon;
import java.io.IOException;
import Modos.NewJFrame1;
import java.awt.Image;
import java.io.IOException;
import javax.swing.Icon;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author alexsander
 */
public class Form1 extends javax.swing.JFrame {

    int acertos = 0, erros = 0, captura = 0;
    Image imagem;
    int min = 1, max = 5;

    private MapaEstadosBrasil MapEstadosBrasil = new MapaEstadosBrasil();
    private static Mapa map = new Mapa();
    public static Random RND = new Random();

    private static Estados Estate = new Estados();
    private static Questão guest;
    private static Rodada round = new Rodada();
//gera numero aletoio entre 1 e 5

    public int Random() {
        java.util.Random rand = new java.util.Random();
        int randomNum = rand.nextInt((max - min) + 1) + min;
        captura = randomNum;
        return captura;
    }
//seta resposta correta em algum radio buttons

    public void RandomRespostaCorreta() {
        Random();
        if (guest.VerificaMyList(round.randomNum)) {//verificará se a resposta já existe em algum radio buttons para não haver mais de um com a mesma resposta
            if (captura == 1) {
                Resposta1.setText(Estate.estados[round.randomNum]);
            } else if (captura == 2) {
                Resposta2.setText(Estate.estados[round.randomNum]);
            } else if (captura == 3) {
                Resposta3.setText(Estate.estados[round.randomNum]);
            } else if (captura == 4) {
                Resposta4.setText(Estate.estados[round.randomNum]);
            } else if (captura == 5) {
                Resposta5.setText(Estate.estados[round.randomNum]);
            }
        }
    }
//seta texto resposta para os radio buttons

    public void Modifica() {
        Resposta1.setText(Estate.estados[guest.AnswerRandInt(0, 14)]);
        Resposta2.setText(Estate.estados[guest.AnswerRandInt(0, 14)]);
        Resposta3.setText(Estate.estados[guest.AnswerRandInt(0, 14)]);
        Resposta4.setText(Estate.estados[guest.AnswerRandInt(0, 14)]);
        Resposta5.setText(Estate.estados[guest.AnswerRandInt(0, 14)]);
        //RandomRespostaCorreta();
    }
//contabilizo numero de erros e acertos

    public void SetAcertosErros() {
        if (Resposta1.getText() == Estate.estados[round.randomNum] && Resposta1.isSelected() == true
                || Resposta2.getText() == Estate.estados[round.randomNum] && Resposta2.isSelected() == true
                || Resposta3.getText() == Estate.estados[round.randomNum] && Resposta3.isSelected() == true
                || Resposta4.getText() == Estate.estados[round.randomNum] && Resposta4.isSelected() == true
                || Resposta5.getText() == Estate.estados[round.randomNum] && Resposta5.isSelected() == true) {
            int io = 0;
        } else {
            guest.SetListaErros(Estate.estados[round.randomNum]);
        }
    }

    public Form1() {
        initComponents();
        guest = new Questão(acertos, erros);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        imagemMOD1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        seleciona_pla = new javax.swing.JLabel();
        Resposta1 = new javax.swing.JRadioButton();
        Resposta2 = new javax.swing.JRadioButton();
        Resposta5 = new javax.swing.JRadioButton();
        Resposta3 = new javax.swing.JRadioButton();
        Resposta4 = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/proximo.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        seleciona_pla.setText("Selecione:");

        buttonGroup1.add(Resposta1);
        Resposta1.setSelected(true);
        Resposta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Resposta1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(Resposta2);
        Resposta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Resposta2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(Resposta5);
        Resposta5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Resposta5ActionPerformed(evt);
            }
        });

        buttonGroup1.add(Resposta3);
        Resposta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Resposta3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(Resposta4);
        Resposta4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Resposta4ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/play.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(seleciona_pla)
                                .addGap(366, 366, 366))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Resposta1)
                                .addGap(99, 99, 99)
                                .addComponent(Resposta2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Resposta3)
                                .addGap(81, 81, 81)
                                .addComponent(Resposta4)
                                .addGap(13, 13, 13))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(Resposta5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imagemMOD1, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(imagemMOD1, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(seleciona_pla)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Resposta2)
                            .addComponent(Resposta3)
                            .addComponent(Resposta4)
                            .addComponent(Resposta1))
                        .addGap(27, 27, 27)
                        .addComponent(Resposta5)
                        .addGap(20, 20, 20))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Resposta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Resposta2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Resposta2ActionPerformed

    private void Resposta5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Resposta5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Resposta5ActionPerformed

    private void Resposta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Resposta1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Resposta1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        /*ImageIcon icon = new ImageIcon(MapEstadosBrasil[1].getMap());
         imagemMOD1.setIcon(icon);*/
        //Modifica();
        // questao++;
        //Random();
        SetAcertosErros();

        ImageIcon icon = new ImageIcon(MapEstadosBrasil.getMap(round.QuestRandInt(0, 9)));
        imagemMOD1.setIcon(icon);
        Modifica();
        //RandomRespostaCorreta();
        //guest.ClearMyList();

        guest.SetAcertos(acertos);
        guest.SetErros(erros);
        RandomRespostaCorreta();
        guest.GetListaErros();
        guest.ClearMyList();
        //JOptionPane.showMessageDialog(null, "numero de acertos: "+guest.GetAcertos());
        //JOptionPane.showMessageDialog(null, "numero de erros: "+guest.GetErros());

        if (round.ListaCheia()) {
            guest.GetListaErros();
            round.ClearList();
            this.setVisible(false);
            new NewJFrame1().setVisible(true);
            JOptionPane.showMessageDialog(null, "Modo 1 -> Término");
        }
        //-------------------------------------------------------------------------------//
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Resposta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Resposta3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Resposta3ActionPerformed

    private void Resposta4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Resposta4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Resposta4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Random();
        ImageIcon icon = new ImageIcon(MapEstadosBrasil.getMap(round.QuestRandInt(0, 9)));
        imagemMOD1.setIcon(icon);
        Modifica();
        RandomRespostaCorreta();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Resposta1;
    private javax.swing.JRadioButton Resposta2;
    private javax.swing.JRadioButton Resposta3;
    private javax.swing.JRadioButton Resposta4;
    private javax.swing.JRadioButton Resposta5;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel imagemMOD1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel seleciona_pla;
    // End of variables declaration//GEN-END:variables
}
